packages:
  - '.'
  - 'freelancexchain-email-worker'

onlyBuiltDependencies:
  - bcrypt

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - qs
  - browserslist
  - electron-to-chromium
  - caniuse-lite
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
