module.exports = {
  isWeb3Available: jest.fn().mockReturnValue(false),
  getProvider: jest.fn().mockReturnValue(null),
  getWallet: jest.fn().mockReturnValue(null),
  getFreshWallet: jest.fn().mockReturnValue(null),
  resetWeb3Instances: jest.fn(),
  getWalletInfo: jest.fn().mockResolvedValue({ address: '0xmock', balance: BigInt(0), chainId: 1 }),
  getBalance: jest.fn().mockResolvedValue(BigInt(0)),
  sendTransaction: jest.fn().mockResolvedValue({ hash: '0xmock', blockNumber: 1, from: '0xmock', to: '0xmock', value: BigInt(0), gasUsed: BigInt(21000), status: 'success' }),
  getTransactionByHash: jest.fn().mockResolvedValue(null),
  waitForTransaction: jest.fn().mockResolvedValue({ hash: '0xmock', blockNumber: 1, from: '0xmock', to: '0xmock', value: BigInt(0), gasUsed: BigInt(21000), status: 'success' }),
  getGasPrice: jest.fn().mockResolvedValue(BigInt(0)),
  getBlockNumber: jest.fn().mockResolvedValue(1),
  estimateGas: jest.fn().mockResolvedValue(BigInt(21000)),
  formatEther: jest.fn().mockReturnValue('0.0'),
  parseEther: jest.fn().mockReturnValue(BigInt(0)),
  isValidAddress: jest.fn().mockReturnValue(true),
  getChecksumAddress: jest.fn().mockReturnValue('0xmock'),
  signMessage: jest.fn().mockResolvedValue('0xmock-signature'),
  verifyMessage: jest.fn().mockReturnValue('0xmock'),
  getNetworkInfo: jest.fn().mockResolvedValue({ name: 'mock', chainId: 1 }),
  isCorrectNetwork: jest.fn().mockResolvedValue(true),
  deployContract: jest.fn().mockResolvedValue({ address: '0xmock', transactionHash: '0xmock' }),
  getContract: jest.fn().mockReturnValue(null),
  getContractWithSigner: jest.fn().mockReturnValue(null),
};