name: MegaLinter

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  megalinter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Harden-Runner
        uses: step-security/harden-runner@v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: MegaLinter
        uses: oxsecurity/megalinter@v8.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLY_FIXES: none
          YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: pnpm-lock.yaml
          ENABLE_LINTERS: TYPESCRIPT_ES,JSON_JSONLINT,YAML_YAMLLINT,MARKDOWN_MARKDOWNLINT,DOCKERFILE_HADOLINT,SOLIDITY_SOLHINT
          DISABLE_TELEMETRY: true
          SHOW_ELAPSED_TIME: true
          VALIDATE_ALL_CODEBASE: true

      - name: Upload MegaLinter artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log
